### ISSUE TITLE
Funqy integration no longer compiles with Quarkus 1.11.0.Beta

### ISSUE THREAD

**Issue by geoand** [quarkusio/qson#10]
It seems like https://github.com/quarkusio/quarkus/commit/f757778b751e6ed54aad3fe95aa5b4965d741c6b removed  `FunctionInvoker#getInputGenericType` which is needed by `FunqyHttpBindingRecorder#init`

**Comment by gsmet** [comment]
I think it can probably just be replaced by `getInputType()`.

Anyway, qson needs to be added to the Ecosystem CI.

**Comment by geoand** [comment]
This is still a problem with `1.11.0.CR1`.

@patriot1burke what is the plan for this?

**Comment by geoand** [comment]
@patriot1burke is this on your radar? It would be nice to have a fix for Quarkus 1.11

**Comment by patriot1burke** [comment]
Yes, i have to bang out some AWS work first though.

**Comment by geoand** [comment]
Gotcha, thanks

**Comment by patriot1burke** [comment]
Fixed.  Will be in next release

**Comment by geoand** [comment]
Great, thanks!
