### ISSUE TITLE
Adding QSon to the benchmark

### ISSUE THREAD

**Issue by agoncal** [quarkusio/qson#21]
I wonder if QSon supports all the features of this benchmark. [QSon](https://github.com/quarkusio/qson) is now used in Quarkus as the default JSon mapper and is pretty fast (does bytecode generation)

**Comment by agoncal** [comment]
@gsmet sorry, totally mixed up my tabs and opened an issue on the wrong repo ;o)

**Comment by gsmet** [comment]
Well, my comment is not about the wrong repo, it's about the wrong assertion :).
